export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  WECHAT_NOT_CONFIGURED: 'WECHAT_NOT_CONFIGURED',
  WECHAT_AUTH_FAILED: 'WECHAT_AUTH_FAILED',
  NO_PASSWORD: 'NO_PASSWORD',
  WRONG_PASSWORD: 'WRONG_PASSWORD'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
